In [4]:
import numpy as np

In [22]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [69]:
b = np.array([[1,3,4],[5,6,7]])
print(b)

[[1 3 4]
 [5 6 7]]


In [16]:
a.shape

(3,)

In [18]:
b.shape

(2, 3)

In [26]:
a.itemsize

2

In [30]:
a.nbytes

6

In [6]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
c[1, 5]

13

In [10]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
c[:, 2]

array([ 3, 10])

In [59]:
c[0, 1:-1:2]

array([2, 4, 6])

In [63]:
c[1, -2]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [65]:
c[:, -3]=[20,24]
print(c)

[[ 1  2  3  4 20  6  7]
 [ 8  9 10 11 24 20 14]]


In [14]:
c[:, -4]=[2,3]
print(c)

[[ 1  2  3  2  5  6  7]
 [ 8  9 10  3 12 13 14]]


In [32]:
d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
d[0,1,1]

4

In [40]:
d[:,1,1]

array([4, 8])

In [42]:
d[:,1,:]=[[8,7],[4,6]]
print(d)

[[[1 2]
  [8 7]]

 [[5 6]
  [4 6]]]


In [58]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [60]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [62]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [71]:
np.full(b.shape,2)

array([[2, 2, 2],
       [2, 2, 2]])

In [81]:
np.random.rand(4,2,3)

array([[[0.53785126, 0.67074856, 0.51753035],
        [0.3192114 , 0.88581195, 0.50346724]],

       [[0.13721015, 0.99881177, 0.75332671],
        [0.44371298, 0.57828841, 0.64220569]],

       [[0.891725  , 0.9505381 , 0.52775509],
        [0.62099584, 0.3273365 , 0.20834836]],

       [[0.81663406, 0.97324625, 0.09827729],
        [0.16371804, 0.17796715, 0.61875721]]])

In [101]:
np.random.randint(3,8, size=(3,3))

array([[7, 7, 4],
       [3, 3, 6],
       [7, 4, 6]])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr = np.array([[1,2,3]])
np.repeat(arr,3, axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [38]:
one = np.ones((5,5))
print(one)
z = np.zeros((3,3))
#print(z)
z[1,1]=9
print(z)
one[1:4,1:4]=z
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
e = np.array([1,2,3])
f = e.copy()
f[0]=4
print(e)
print(f)

[1 2 3]
[4 2 3]


In [44]:
e + 2

array([5, 6, 7])

In [46]:
e / 2

array([1.5, 2. , 2.5])

In [48]:
np.cos(e)

array([-0.9899925 , -0.65364362,  0.28366219])

In [78]:
h = np.ones((2,3))
i = np.full((3,2),2)
print(h)
print(i)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [82]:
np.matmul(h,i)

array([[6., 6.],
       [6., 6.]])

In [86]:
#find the determinate
j = np.identity(4)
np.linalg.det(j)

1.0

In [96]:
#statistics
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [94]:
np.max(stats)

6

In [98]:
np.sum(stats)

21

In [100]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [102]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [110]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [114]:
np.genfromtxt('1.txt', delimiter=',')

FileNotFoundError: 1.txt not found.

In [116]:
import os
print(os.getcwd())

C:\Users\User


In [118]:
import os
os.chdir('E:\\Jupyter')


In [120]:
import os
print(os.getcwd())

E:\Jupyter


In [122]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])